log:
  default:
    format: json
    level: info
    verbosity: 0
    output:
      stdout:
        enable: true
  fanouts:
    - format: json
      level: error
      verbosity: 4
      output:
        stderr:
          enable: true
    - format: json
      level: debug
      verbosity: 4
      output:
        file:
          enable: true
          path: /var/log/ddns/ddns.log
          maxSize: 10mb
          maxAge: 7d
          maxBackups: 10
          compress: true

ddns:
  interval: 30m

  provider:
    provider: aliyun
    aliyun:
      endpoint: "dns.aliyuncs.com"
      accessKeyId:
      accesskeySecret:

  configs:
    - enable: false
      record:
        type: "A"
        rr: "template"
        domain: "example.com"
      provider:
        type: "interface"
        interface:
          interface: "ens18"
          prefix: "192.168"

    - enable: false
      record:
        type: "A"
        rr: "*.template"
        domain: "example.com"
      provider:
        type: "interface"
        interface:
          interface: "ens18"
          prefix: "192.168"

    - enable: false
      record:
        type: "AAAA"
        rr: "template"
        domain: "example.com"
      provider:
        type: "command"
        command: "ifconfig ens18 | grep inet6 | awk '{print $2}' | grep '^240e'"

    - enable: false
      record:
        type: "AAAA"
        rr: "template"
        domain: "example.com"
      provider:
        type: "command"
        command: "ifconfig ens18 | grep inet6 | awk '{print $2}' | grep '^240e'"
