


accesskeyid:
accesskeysecret:
domain:
updateintervalmin: 60
ddnss:
  - enable: false
    type: "A"
    rr: "template.home"
    interface: "ens18"
    prefix: "192.168"
  - enable: false
    type: "A"
    rr: "*.template.home"
    interface: "ens18"
    prefix: "192.168"
  - enable: false
    type: "AAAA"
    rr: "template6.home"
    interface: "ens18"
    prefix: "240e"
  - enable: false
    type: "AAAA"
    rr: "*.template6.home"
    interface: "ens18"
    prefix: "240e"
