log:
  default:
    format: json
    level: info
    verbosity: 0
    output:
      stdout:
        enable: true
  fanouts:
    - format: json
      level: error
      verbosity: 4
      output:
        stderr:
          enable: true
    - format: json
      level: debug
      verbosity: 4
      output:
        file:
          enable: true
          path: /var/log/ddns/ddns.log
          maxSize: 10mb
          maxAge: 7d
          maxBackups: 10
          compress: true

interval: 30m

aliyun:
  accessKeyId:
  accesskeySecret:

ddnss:
  - enable: false
    type: "A"
    rr: "template.home"
    domain: "example.com"
    interface: "ens18"
    prefix: "192.168"
  - enable: false
    type: "A"
    rr: "*.template.home"
    domain: "example.com"
    interface: "ens18"
    prefix: "192.168"
  - enable: false
    type: "AAAA"
    rr: "template.home"
    domain: "example.com"
    interface: "ens18"
    prefix: "240e"
  - enable: false
    type: "AAAA"
    rr: "*.template.home"
    domain: "example.com"
    interface: "ens18"
    prefix: "240e"
